CREATE TABLE IF NOT EXISTS teams (
  id INT AUTO_INCREMENT PRIMARY KEY,
  yahoo_team_id VARCHAR(50) NOT NULL UNIQUE,
  team_name VARCHAR(100) NOT NULL,
  is_user_team BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
