CREATE TABLE IF NOT EXISTS players (
  id INT AUTO_INCREMENT PRIMARY KEY,
  yahoo_player_id VARCHAR(50),
  player_id INT,
  team_id INT,
  name VARCHAR(100) NOT NULL,
  mlb_team VARCHAR(10),
  position VARCHAR(10),
  status ENUM('rostered', 'free_agent') DEFAULT 'free_agent',
  is_c TINYINT(1) DEFAULT 0,
  is_1b TINYINT(1) DEFAULT 0,
  is_2b TINYINT(1) DEFAULT 0,
  is_3b TINYINT(1) DEFAULT 0,
  is_ss TINYINT(1) DEFAULT 0,
  is_of TINYINT(1) DEFAULT 0,
  is_util TINYINT(1) DEFAULT 0,
  is_sp TINYINT(1) DEFAULT 0,
  is_rp TINYINT(1) DEFAULT 0,
  eligible_positions TEXT,
  selected_position VARCHAR(50),
  headshot_url VARCHAR(500),
  normalised_name VARCHAR(100),
  FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE,
  UNIQUE KEY unique_player_id_position (player_id, position),
  UNIQUE KEY unique_yahoo_player_id (yahoo_player_id),
  INDEX idx_sp (is_sp),
  INDEX idx_rp (is_rp),
  INDEX idx_is_of (is_of),
  INDEX idx_team_id (team_id),
  INDEX idx_normalised_name_ps (normalised_name)
);
