CREATE TABLE IF NOT EXISTS player_game_logs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  player_id INT NOT NULL,
  game_date DATE NOT NULL,
  opponent VARCHAR(10),
  is_home BOOLEAN,
  position VARCHAR(10),
  ab INT,
  h INT,
  r INT,
  rbi INT,
  hr INT,
  sb INT,
  bb INT,
  k INT,
  ip FLOAT,
  er INT,
  hits_allowed INT,
  walks_allowed INT,
  strikeouts INT,
  qs tinyint(1),
  sv tinyint(1),
  hld tinyint(1),
  nrfi tinyint(1),
  fantasy_points FLOAT,
  team VARCHAR(10),
  game_id VARCHAR(20),
  normalised_name VARCHAR(100),

  singles INT DEFAULT 0,
  doubles INT DEFAULT 0,
  triples INT DEFAULT 0,
  total_bases INT DEFAULT 0,
  sac_flies INT DEFAULT 0,
  hit_by_pitch INT DEFAULT 0,
  ground_outs INT DEFAULT 0,
  air_outs INT DEFAULT 0,
  left_on_base INT DEFAULT 0,
  ground_into_dp INT DEFAULT 0,
  batters_faced INT DEFAULT 0,
  wild_pitches INT DEFAULT 0,
  balks INT DEFAULT 0,
  home_runs_allowed INT DEFAULT 0,
  inherited_runners INT DEFAULT 0,
  inherited_runners_scored INT DEFAULT 0,
  UNIQUE KEY unique_player_game (player_id, position, game_id),
  INDEX idx_normalised_name_ps_logs (normalised_name)
);
