CREATE TABLE IF NOT EXISTS player_rolling_stats (
  id INT AUTO_INCREMENT PRIMARY KEY,
  player_id INT NOT NULL,
  span_days INT NOT NULL,
  split_type VARCHAR(10) DEFAULT 'overall',
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  games INT DEFAULT 0,
  rbi INT DEFAULT 0,
  runs INT DEFAULT 0,
  hr INT DEFAULT 0,
  sb INT DEFAULT 0,
  hits INT DEFAULT 0,
  abs INT DEFAULT 0,
  avg DECIMAL(4,3) DEFAULT 0.000,
  k INT DEFAULT 0,
  strikeouts INT DEFAULT 0,
  ip DECIMAL(5,2) DEFAULT 0.00,
  er INT DEFAULT 0,
  qs INT DEFAULT 0,
  sv INT DEFAULT 0,
  hld INT DEFAULT 0,
  nrfi INT DEFAULT 0,
  whip DECIMAL(4,2) DEFAULT 0.00,
  era DECIMAL(5,2) DEFAULT 0.00,
  normalised_name VARCHAR(100),
  position VARCHAR(10),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY unique_player_span (player_id, position, span_days, split_type),
  INDEX idx_normalised_name_ts (normalised_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
