CREATE TABLE IF NOT EXISTS player_rolling_stats_percentiles (
  id INT AUTO_INCREMENT PRIMARY KEY,
  player_id INT NOT NULL,
  span_days INT NOT NULL,
  split_type VARCHAR(10) NOT NULL,
  rbi_pct DECIMAL(5,2) DEFAULT 0.00,
  runs_pct DECIMAL(5,2) DEFAULT 0.00,
  hr_pct DECIMAL(5,2) DEFAULT 0.00,
  sb_pct DECIMAL(5,2) DEFAULT 0.00,
  hits_pct DECIMAL(5,2) DEFAULT 0.00,
  avg_pct DECIMAL(5,2) DEFAULT 0.00,
  k_pct DECIMAL(5,2) DEFAULT 0.00,
  strikeouts_pct DECIMAL(5,2) DEFAULT 0.00,
  era_pct DECIMAL(5,2) DEFAULT 0.00,
  whip_pct DECIMAL(5,2) DEFAULT 0.00,
  er_pct DECIMAL(5,2) DEFAULT 0.00,
  qs_pct DECIMAL(5,2) DEFAULT 0.00,
  sv_pct DECIMAL(5,2) DEFAULT 0.00,
  hld_pct DECIMAL(5,2) DEFAULT 0.00,
  nrfi_pct DECIMAL(5,2) DEFAULT 0.00,
  reliability_score TINYINT UNSIGNED DEFAULT 0,
  is_reliable BOOLEAN GENERATED ALWAYS AS (reliability_score >= 70) STORED,
  normalised_name VARCHAR(100),
  position VARCHAR(10),
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY unique_player_span (player_id, position, span_days, split_type),
  INDEX idx_normalised_name_ps_percentiles (normalised_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
