CREATE TABLE IF NOT EXISTS player_advanced_rolling_stats (
  id INT AUTO_INCREMENT PRIMARY KEY,
  player_id INT NOT NULL,
  span_days INT NOT NULL,
  split_type VARCHAR(10) DEFAULT 'overall',
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,

  obp DECIMAL(4,3) DEFAULT 0.000,
  slg DECIMAL(4,3) DEFAULT 0.000,
  ops DECIMAL(4,3) DEFAULT 0.000,
  bb_rate DECIMAL(5,2) DEFAULT 0.00,
  k_rate DECIMAL(5,2) DEFAULT 0.00,
  babip DECIMAL(5,3) DEFAULT 0.000,
  iso DECIMAL(4,3) DEFAULT 0.000,
  contact_pct DECIMAL(5,2) DEFAULT 0.00,
  gb_fb_ratio DECIMAL(4,3) DEFAULT 0.000,
  lob_batting_pct DECIMAL(5,2) DEFAULT 0.00,
  woba DECIMAL(4,3) DEFAULT 0.000,
  woba_plus DECIMAL(5,1) DEFAULT 0.0,
  obp_plus DECIMAL(5,1) DEFAULT 0.0,
  slg_plus DECIMAL(5,1) DEFAULT 0.0,
  ops_plus DECIMAL(5,1) DEFAULT 0.0,
  wraa DECIMAL(5,1) DEFAULT 0.0,

  inherited_runners INT DEFAULT 0,
  inherited_runners_scored INT DEFAULT 0,
  irs_pct DECIMAL(5,2) DEFAULT 0.00,
  fip DECIMAL(5,2) DEFAULT 0.00,
  k_per_9 DECIMAL(5,2) DEFAULT 0.00,
  bb_per_9 DECIMAL(5,2) DEFAULT 0.00,
  hr_per_9 DECIMAL(5,2) DEFAULT 0.00,
  k_bb_ratio DECIMAL(5,2) DEFAULT 0.00,
  lob_pitching_pct DECIMAL(5,2) DEFAULT 0.00,
  fip_minus DECIMAL(5,1) DEFAULT 0.0,
  era_minus DECIMAL(6,1) DEFAULT 0.0,

  normalised_name VARCHAR(100),
  position VARCHAR(10),
  abs INT DEFAULT 0,
  ip DECIMAL(5,2) DEFAULT 0.00,
  games INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  UNIQUE KEY unique_player_span (player_id, position, span_days, split_type),
  INDEX idx_normalised_name_ars (normalised_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
