CREATE TABLE IF NOT EXISTS player_advanced_rolling_stats_percentiles (
  id INT AUTO_INCREMENT PRIMARY KEY,
  player_id INT NOT NULL,
  span_days INT NOT NULL,
  split_type VARCHAR(10) NOT NULL,

  obp_pct DECIMAL(5,2) DEFAULT 0.00,
  slg_pct DECIMAL(5,2) DEFAULT 0.00,
  ops_pct DECIMAL(5,2) DEFAULT 0.00,
  bb_rate_pct DECIMAL(5,2) DEFAULT 0.00,
  k_rate_pct DECIMAL(5,2) DEFAULT 0.00,
  babip_pct DECIMAL(5,2) DEFAULT 0.00,
  iso_pct DECIMAL(5,2) DEFAULT 0.00,
  contact_pct_pct DECIMAL(5,2) DEFAULT 0.00,
  gb_fb_ratio_pct DECIMAL(5,2) DEFAULT 0.00,
  lob_batting_pct_pct DECIMAL(5,2) DEFAULT 0.00,
  woba_pct DECIMAL(5,2) DEFAULT 0.00,
  woba_plus_pct DECIMAL(5,2) DEFAULT 0.00,
  obp_plus_pct DECIMAL(5,2) DEFAULT 0.00,
  slg_plus_pct DECIMAL(5,2) DEFAULT 0.00,
  ops_plus_pct DECIMAL(5,2) DEFAULT 0.00,
  wraa_pct DECIMAL(5,2) DEFAULT 0.00,

  inherited_runners_pct DECIMAL(5,2) DEFAULT 0.00,
  inherited_runners_scored_pct DECIMAL(5,2) DEFAULT 0.00,
  irs_pct_pct DECIMAL(5,2) DEFAULT 0.00,
  fip_pct DECIMAL(5,2) DEFAULT 0.00,
  k_per_9_pct DECIMAL(5,2) DEFAULT 0.00,
  bb_per_9_pct DECIMAL(5,2) DEFAULT 0.00,
  hr_per_9_pct DECIMAL(5,2) DEFAULT 0.00,
  k_bb_ratio_pct DECIMAL(5,2) DEFAULT 0.00,
  lob_pitching_pct_pct DECIMAL(5,2) DEFAULT 0.00,
  fip_minus_pct DECIMAL(5,2) DEFAULT 0.00,
  era_minus_pct DECIMAL(5,2) DEFAULT 0.00,

  reliability_score TINYINT UNSIGNED,
  is_reliable BOOLEAN GENERATED ALWAYS AS (reliability_score >= 70) STORED,
  normalised_name VARCHAR(100),
  position VARCHAR(10),
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  UNIQUE KEY unique_player_span (player_id, position, span_days, split_type),
  INDEX idx_normalised_name_ars_percentiles (normalised_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
