CREATE TABLE IF NOT EXISTS team_game_logs (
  team VARCHAR(10),
  game_date DATE,
  opponent VARCHAR(10),
  is_home BOOLEAN,
  is_win BOOLEAN,
  runs_scored INT,
  runs_allowed INT,
  avg FLOAT,
  obp FLOAT,
  slg FLOAT,
  ops FLOAT,
  er INT,
  era FLOAT,
  whip FLOAT,
  strikeouts INT,
  walks INT,
  ip FLOAT,
  hits_allowed INT,
  nrfi tinyint(1),
  game_id VARCHAR(20),

  singles INT DEFAULT 0,
  doubles INT DEFAULT 0,
  triples INT DEFAULT 0,
  total_bases INT DEFAULT 0,
  sac_flies INT DEFAULT 0,
  hit_by_pitch INT DEFAULT 0,
  ground_outs INT DEFAULT 0,
  air_outs INT DEFAULT 0,
  left_on_base INT DEFAULT 0,
  ground_into_dp INT DEFAULT 0,
  batters_faced INT DEFAULT 0,
  wild_pitches INT DEFAULT 0,
  balks INT DEFAULT 0,
  home_runs_allowed INT DEFAULT 0,
  inherited_runners INT DEFAULT 0,
  inherited_runners_scored INT DEFAULT 0,
  PRIMARY KEY (team, game_date)
);
