CREATE TABLE IF NOT EXISTS player_season_stats (
  id INT AUTO_INCREMENT PRIMARY KEY,
  player_id INT,
  fangraphs_player_id INT,
  normalised_name VARCHAR(100),
  team VARCHAR(10),
  position VARCHAR(10),

  games INT,
  pa INT,
  ab INT,
  hits INT,
  hr INT,
  rbi INT,
  runs INT,
  sb INT,
  avg DECIMAL(5,3),
  obp DECIMAL(5,3),
  slg DECIMAL(5,3),
  ops DECIMAL(5,3),
  bb_rate DECIMAL(5,2),
  k_rate DECIMAL(5,2),

  iso DECIMAL(5,3),
  babip DECIMAL(5,3),
  woba DECIMAL(5,3),
  wrc_plus INT,
  wraa DECIMAL(6,2),

  barrel_pct DECIMAL(5,2),
  hard_hit_pct DECIMAL(5,2),
  avg_ev DECIMAL(5,2),
  max_ev DECIMAL(5,2),
  sweet_spot_pct DECIMAL(5,2),

  chase_pct DECIMAL(5,2),
  contact_pct DECIMAL(5,2),
  zone_contact_pct DECIMAL(5,2),
  whiff_pct DECIMAL(5,2),

  ip DECIMAL(6,2),
  era DECIMAL(5,2),
  whip DECIMAL(5,2),
  fip DECIMAL(5,2),
  x_fip DECIMAL(5,2),
  k_per_9 DECIMAL(5,2),
  bb_per_9 DECIMAL(5,2),
  hr_per_9 DECIMAL(5,2),
  k_pct DECIMAL(5,2),
  bb_pct DECIMAL(5,2),
  lob_pct DECIMAL(5,2),
  csw_pct DECIMAL(5,2),
  swinging_strike_pct DECIMAL(5,2),
  ground_ball_pct DECIMAL(5,2),
  fly_ball_pct DECIMAL(5,2),

  qs INT,
  sv INT,
  hld INT,

  sprint_speed DECIMAL(5,2),
  age INT,
  last_updated DATETIME DEFAULT CURRENT_TIMESTAMP,

  UNIQUE KEY unique_player_season (player_id, position),
  UNIQUE KEY unique_fangraphs_player_season (fangraphs_player_id, position),
  INDEX idx_normalised_name_ps (normalised_name),
  INDEX idx_player_id (player_id)
);
