CREATE TABLE IF NOT EXISTS player_season_stats_percentiles (
  id INT AUTO_INCREMENT PRIMARY KEY,
  player_id INT,
  fangraphs_player_id INT,
  normalised_name VARCHAR(100),
  team VARCHAR(10),
  position VARCHAR(10),

  hits_pct INT,
  hr_pct INT,
  rbi_pct INT,
  runs_pct INT,
  sb_pct INT,
  avg_pct DECIMAL(5,2),
  obp_pct DECIMAL(5,2),
  slg_pct DECIMAL(5,2),
  ops_pct DECIMAL(5,2),
  bb_rate_pct DECIMAL(5,2),
  k_rate_pct DECIMAL(5,2),

  iso_pct DECIMAL(5,2),
  babip_pct DECIMAL(5,2),
  woba_pct DECIMAL(5,2),
  wrc_plus_pct INT,
  wraa_pct DECIMAL(6,2),

  barrel_pct_pct DECIMAL(5,2),
  hard_hit_pct_pct DECIMAL(5,2),
  avg_ev_pct DECIMAL(5,2),
  max_ev_pct DECIMAL(5,2),
  sweet_spot_pct_pct DECIMAL(5,2),

  chase_pct_pct DECIMAL(5,2),
  contact_pct_pct DECIMAL(5,2),
  zone_contact_pct_pct DECIMAL(5,2),
  whiff_pct_pct DECIMAL(5,2),

  era_pct DECIMAL(5,2),
  whip_pct DECIMAL(5,2),
  fip_pct DECIMAL(5,2),
  x_fip_pct DECIMAL(5,2),
  k_per_9_pct DECIMAL(5,2),
  bb_per_9_pct DECIMAL(5,2),
  hr_per_9_pct DECIMAL(5,2),
  k_pct_pct DECIMAL(5,2),
  bb_pct_pct DECIMAL(5,2),
  lob_pct_pct DECIMAL(5,2),
  csw_pct_pct DECIMAL(5,2),
  swinging_strike_pct_pct DECIMAL(5,2),
  ground_ball_pct_pct DECIMAL(5,2),
  fly_ball_pct_pct DECIMAL(5,2),

  qs_pct INT,
  sv_pct INT,
  hld_pct INT,

  sprint_speed_pct DECIMAL(5,2),
  age_pct INT,
  last_updated DATETIME DEFAULT CURRENT_TIMESTAMP,

  reliability_score TINYINT UNSIGNED,
  is_reliable BOOLEAN GENERATED ALWAYS AS (reliability_score >= 70) STORED,

  UNIQUE KEY unique_player_season_percentiles (player_id, position),
  UNIQUE KEY unique_fangraphs_player_season_percentiles (fangraphs_player_id, position),
  INDEX idx_normalised_name_ps_percentiles (normalised_name),
  INDEX idx_player_id_percentiles (player_id)
);
