CREATE TABLE IF NOT EXISTS team_season_stats (
  team VARCHAR(10) PRIMARY KEY,

  games_played INT,
  pa INT,
  ab INT,
  runs INT,
  hits INT,
  hr INT,
  rbi INT,
  sb INT,
  avg DECIMAL(5,3),
  obp DECIMAL(5,3),
  slg DECIMAL(5,3),
  ops DECIMAL(5,3),
  bb_rate DECIMAL(5,2),
  k_rate DECIMAL(5,2),
  woba DECIMAL(5,3),
  wrc_plus INT,
  iso DECIMAL(5,3),
  babip DECIMAL(5,3),

  ip DECIMAL(6,2),
  era DECIMAL(5,2),
  whip DECIMAL(5,2),
  fip DECIMAL(5,2),
  x_fip DECIMAL(5,2),
  k_per_9 DECIMAL(5,2),
  bb_per_9 DECIMAL(5,2),
  hr_per_9 DECIMAL(5,2),
  k_pct DECIMAL(5,2),
  bb_pct DECIMAL(5,2),
  swinging_strike_pct DECIMAL(5,2),
  csw_pct DECIMAL(5,2),
  ground_ball_pct DECIMAL(5,2),
  fly_ball_pct DECIMAL(5,2),
  lob_pct DECIMAL(5,2),

  barrel_pct DECIMAL(5,2),
  hard_hit_pct DECIMAL(5,2),
  avg_ev DECIMAL(5,2),
  war DECIMAL(5,2),

  last_updated DATETIME DEFAULT CURRENT_TIMESTAMP
);
